version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: konstantin
      POSTGRES_PASSWORD: konstantin
      POSTGRES_DB: user
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"  # Внутренний порт приложения
    depends_on:
      - backend
    networks:
      - app-network

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache
    ports:
      - "8004:80"  # Изменен порт хоста на 8004
    volumes:
      - ./apache/conf/sites.conf:/usr/local/apache2/conf/sites.conf
      - ./apache/html:/usr/local/apache2/htdocs/  # Для статических файлов (если необходимо)
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
